# Generated by Django 6.0.4 on 2026-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='test-slug'),
            preserve_default=False,
        ),
    ]
